// This file is auto-generated by @hey-api/openapi-ts

export const Body_courses_upload_course_coverSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_courses-upload_course_cover'
} as const;

export const Body_lessons_upload_lesson_coverSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_lessons-upload_lesson_cover'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: 'password'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const Body_users_upload_avatar_meSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_users-upload_avatar_me'
} as const;

export const Body_users_upload_cover_meSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_users-upload_cover_me'
} as const;

export const CategoriesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CategoryPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'CategoriesPublic'
} as const;

export const CategoryPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['name', 'id'],
    title: 'CategoryPublic'
} as const;

export const CourseCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'Title'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'CourseCreate'
} as const;

export const CoursePublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'Title'
        },
        cover_image: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cover Image'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 4000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        description_video: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description Video'
        },
        short_description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 512
                },
                {
                    type: 'null'
                }
            ],
            title: 'Short Description'
        },
        what_you_will_learn: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'What You Will Learn'
        },
        target_audience: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Target Audience'
        },
        requirements: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Requirements'
        },
        how_it_works: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'How It Works'
        },
        what_you_get: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'What You Get'
        },
        hours_week: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Hours Week'
        },
        hours_total: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Hours Total'
        },
        has_certificate: {
            type: 'boolean',
            title: 'Has Certificate',
            default: false
        },
        difficulty_level: {
            '$ref': '#/components/schemas/DifficultyLevel',
            default: 1
        },
        is_published: {
            type: 'boolean',
            title: 'Is Published',
            default: false
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        datetime_create: {
            type: 'string',
            format: 'date-time',
            title: 'Datetime Create'
        },
        datetime_update: {
            type: 'string',
            format: 'date-time',
            title: 'Datetime Update'
        },
        author_id: {
            type: 'string',
            format: 'uuid',
            title: 'Author Id'
        },
        language_id: {
            type: 'integer',
            title: 'Language Id'
        },
        category_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category Id'
        },
        subcategory_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Subcategory Id'
        },
        is_favorite: {
            type: 'boolean',
            title: 'Is Favorite',
            default: false
        },
        students_count: {
            type: 'integer',
            title: 'Students Count',
            default: 0
        },
        is_enrolled: {
            type: 'boolean',
            title: 'Is Enrolled',
            default: false
        }
    },
    type: 'object',
    required: ['title', 'id', 'datetime_create', 'datetime_update', 'author_id', 'language_id'],
    title: 'CoursePublic'
} as const;

export const CourseUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        cover_image: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cover Image'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        description_video: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description Video'
        },
        short_description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500,
                    minLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Short Description'
        },
        what_you_will_learn: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'What You Will Learn'
        },
        target_audience: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Target Audience'
        },
        requirements: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Requirements'
        },
        how_it_works: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'How It Works'
        },
        what_you_get: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'What You Get'
        },
        hours_week: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Hours Week'
        },
        hours_total: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Hours Total'
        },
        has_certificate: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Has Certificate'
        },
        difficulty_level: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/DifficultyLevel'
                },
                {
                    type: 'null'
                }
            ]
        },
        language_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Language Id'
        },
        category_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category Id'
        },
        subcategory_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Subcategory Id'
        }
    },
    type: 'object',
    title: 'CourseUpdate'
} as const;

export const CoursesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CoursePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'CoursesPublic'
} as const;

export const DifficultyLevelSchema = {
    type: 'integer',
    enum: [1, 2, 3],
    title: 'DifficultyLevel'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const LanguagePublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 20,
            title: 'Name'
        },
        code: {
            type: 'string',
            maxLength: 2,
            title: 'Code'
        },
        id: {
            type: 'integer',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['name', 'code', 'id'],
    title: 'LanguagePublic'
} as const;

export const LanguagesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/LanguagePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'LanguagesPublic'
} as const;

export const LessonCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'Title'
        },
        cover_image: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cover Image'
        },
        language_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Language Id'
        },
        allow_comments: {
            type: 'boolean',
            title: 'Allow Comments',
            default: true
        },
        position: {
            type: 'integer',
            title: 'Position',
            default: 0
        }
    },
    type: 'object',
    required: ['title'],
    title: 'LessonCreate'
} as const;

export const LessonPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'Title'
        },
        cover_image: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cover Image'
        },
        language_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Language Id'
        },
        allow_comments: {
            type: 'boolean',
            title: 'Allow Comments',
            default: true
        },
        position: {
            type: 'integer',
            title: 'Position',
            default: 0
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        module_id: {
            type: 'string',
            format: 'uuid',
            title: 'Module Id'
        }
    },
    type: 'object',
    required: ['title', 'id', 'module_id'],
    title: 'LessonPublic'
} as const;

export const LessonUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        cover_image: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cover Image'
        },
        language_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Language Id'
        },
        allow_comments: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Allow Comments'
        },
        position: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Position'
        }
    },
    type: 'object',
    title: 'LessonUpdate'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const MetaCategoriesWithChildrenPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/MetaCategoryWithSubcategoriesPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'MetaCategoriesWithChildrenPublic'
} as const;

export const MetaCategoryWithSubcategoriesPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        category_id: {
            type: 'string',
            format: 'uuid',
            title: 'Category Id'
        },
        subcategories: {
            items: {
                '$ref': '#/components/schemas/SubcategoryPublic'
            },
            type: 'array',
            title: 'Subcategories',
            default: []
        }
    },
    type: 'object',
    required: ['name', 'id', 'category_id'],
    title: 'MetaCategoryWithSubcategoriesPublic'
} as const;

export const ModuleCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        position: {
            type: 'integer',
            title: 'Position',
            default: 0
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ModuleCreate'
} as const;

export const ModulePublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 256
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        position: {
            type: 'integer',
            title: 'Position',
            default: 0
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        course_id: {
            type: 'string',
            format: 'uuid',
            title: 'Course Id'
        }
    },
    type: 'object',
    required: ['title', 'id', 'course_id'],
    title: 'ModulePublic'
} as const;

export const ModuleUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        position: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Position'
        }
    },
    type: 'object',
    title: 'ModuleUpdate'
} as const;

export const ModuleWithLessonsSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 256
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        position: {
            type: 'integer',
            title: 'Position',
            default: 0
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        course_id: {
            type: 'string',
            format: 'uuid',
            title: 'Course Id'
        },
        lessons: {
            items: {
                '$ref': '#/components/schemas/LessonPublic'
            },
            type: 'array',
            title: 'Lessons',
            default: []
        }
    },
    type: 'object',
    required: ['title', 'id', 'course_id'],
    title: 'ModuleWithLessons'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        first_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'First Name'
        },
        last_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'PrivateUserCreate'
} as const;

export const SetLanguageSchema = {
    properties: {
        language_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Language Id'
        }
    },
    type: 'object',
    title: 'SetLanguage'
} as const;

export const StepCreateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        step_type: {
            '$ref': '#/components/schemas/StepType',
            default: 0
        },
        position: {
            type: 'integer',
            title: 'Position',
            default: 0
        },
        content: {
            additionalProperties: true,
            type: 'object',
            title: 'Content'
        }
    },
    type: 'object',
    title: 'StepCreate'
} as const;

export const StepPublicSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        step_type: {
            '$ref': '#/components/schemas/StepType',
            default: 0
        },
        position: {
            type: 'integer',
            title: 'Position',
            default: 0
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        lesson_id: {
            type: 'string',
            format: 'uuid',
            title: 'Lesson Id'
        },
        content: {
            additionalProperties: true,
            type: 'object',
            title: 'Content'
        }
    },
    type: 'object',
    required: ['id', 'lesson_id'],
    title: 'StepPublic'
} as const;

export const StepTypeSchema = {
    type: 'integer',
    enum: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14],
    title: 'StepType'
} as const;

export const StepUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        step_type: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/StepType'
                },
                {
                    type: 'null'
                }
            ]
        },
        position: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Position'
        },
        content: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content'
        }
    },
    type: 'object',
    title: 'StepUpdate'
} as const;

export const SubcategoryPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        category_id: {
            type: 'string',
            format: 'uuid',
            title: 'Category Id'
        },
        meta_category_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Meta Category Id'
        }
    },
    type: 'object',
    required: ['name', 'id', 'category_id'],
    title: 'SubcategoryPublic'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        refresh_token: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Refresh Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        first_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'First Name'
        },
        last_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Name'
        },
        password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        first_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'First Name'
        },
        last_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        language_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Language Id'
        },
        is_staff: {
            type: 'boolean',
            title: 'Is Staff',
            default: false
        },
        is_teacher: {
            type: 'boolean',
            title: 'Is Teacher',
            default: false
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        description_short: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description Short'
        },
        is_profile_private: {
            type: 'boolean',
            title: 'Is Profile Private',
            default: false
        },
        avatar_image: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avatar Image'
        },
        cover_image: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cover Image'
        },
        city: {
            type: 'string',
            title: 'City',
            default: 'Bishkek'
        },
        date_joined: {
            type: 'string',
            format: 'date-time',
            title: 'Date Joined'
        },
        courses_count: {
            type: 'integer',
            title: 'Courses Count',
            default: 0
        },
        website_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Website Url'
        },
        telegram_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Telegram Url'
        },
        github_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Github Url'
        },
        youtube_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Youtube Url'
        }
    },
    type: 'object',
    required: ['email', 'id', 'date_joined'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Password'
        },
        first_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'First Name'
        },
        last_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        first_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'First Name'
        },
        last_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 40,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        description_short: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description Short'
        },
        city: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 30
                },
                {
                    type: 'null'
                }
            ],
            title: 'City'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        first_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'First Name'
        },
        last_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        city: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 30
                },
                {
                    type: 'null'
                }
            ],
            title: 'City'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        description_short: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description Short'
        },
        website_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Website Url'
        },
        telegram_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Telegram Url'
        },
        github_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Github Url'
        },
        youtube_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Youtube Url'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;