"""add_position_to_module_and_lesson

Revision ID: 1da693b42efb
Revises: f74551b8c440
Create Date: 2025-10-20 05:07:44.505345

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1da693b42efb'
down_revision = 'f74551b8c440'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('position', sa.Integer(), nullable=False))
    op.add_column('module', sa.Column('position', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('module', 'position')
    op.drop_column('lesson', 'position')
    # ### end Alembic commands ###
