"""Add metacategory

Revision ID: 515659286e91
Revises: 4dd30335999e
Create Date: 2025-10-15 23:48:56.315948

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '515659286e91'
down_revision = '4dd30335999e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metacategory',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metacategory_name'), 'metacategory', ['name'], unique=False)
    op.add_column('subcategory', sa.Column('meta_category_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'subcategory', 'metacategory', ['meta_category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subcategory', type_='foreignkey')
    op.drop_column('subcategory', 'meta_category_id')
    op.drop_index(op.f('ix_metacategory_name'), table_name='metacategory')
    op.drop_table('metacategory')
    # ### end Alembic commands ###
