"""Add user.language_id and relations

Revision ID: 54fc48077216
Revises: f89d3c77dd64
Create Date: 2025-10-14 22:15:03.297212

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '54fc48077216'
down_revision = 'f89d3c77dd64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('language_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'language', ['language_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'language_id')
    # ### end Alembic commands ###
