"""add_step_progress_table

Revision ID: 6a7f5f87cfbf
Revises: 9763ce689d3e
Create Date: 2025-10-25 04:25:41.562546

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6a7f5f87cfbf'
down_revision = '9763ce689d3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('step_progress',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('step_id', sa.Uuid(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['step_id'], ['step.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'step_id', name='unique_user_step')
    )
    op.create_index(op.f('ix_step_progress_step_id'), 'step_progress', ['step_id'], unique=False)
    op.create_index(op.f('ix_step_progress_user_id'), 'step_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_step_progress_user_id'), table_name='step_progress')
    op.drop_index(op.f('ix_step_progress_step_id'), table_name='step_progress')
    op.drop_table('step_progress')
    # ### end Alembic commands ###
