"""Add Module and Lesson models

Revision ID: 704e4db1fa07
Revises: c1206036fad4
Create Date: 2025-10-20 04:33:24.637595

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '704e4db1fa07'
down_revision = 'c1206036fad4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lesson',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('allow_comments', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('module_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('course', 'title',
               existing_type=sa.VARCHAR(length=255),
               type_=sqlmodel.sql.sqltypes.AutoString(length=64),
               existing_nullable=False)
    op.drop_column('coursepage', 'is_demo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coursepage', sa.Column('is_demo', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('course', 'title',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=64),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_table('lesson')
    op.drop_table('module')
    # ### end Alembic commands ###
