"""add_course_description_fields

Revision ID: 8dddb96732af
Revises: a9f8b3c45d21
Create Date: 2025-10-20 05:35:27.480028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dddb96732af'
down_revision = 'a9f8b3c45d21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('short_description', sa.String(length=500), nullable=True))
    op.add_column('course', sa.Column('what_you_will_learn', sa.String(length=2000), nullable=True))
    op.add_column('course', sa.Column('target_audience', sa.String(length=2000), nullable=True))
    op.add_column('course', sa.Column('requirements', sa.String(length=2000), nullable=True))
    op.add_column('course', sa.Column('how_it_works', sa.String(length=2000), nullable=True))
    op.add_column('course', sa.Column('what_you_get', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'what_you_get')
    op.drop_column('course', 'how_it_works')
    op.drop_column('course', 'requirements')
    op.drop_column('course', 'target_audience')
    op.drop_column('course', 'what_you_will_learn')
    op.drop_column('course', 'short_description')
    # ### end Alembic commands ###
