"""add_course_description_fields

Revision ID: 8dddb96732af
Revises: a9f8b3c45d21
Create Date: 2025-10-20 05:35:27.480028

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8dddb96732af'
down_revision = 'a9f8b3c45d21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
