"""add_short_description_validation

Revision ID: 9763ce689d3e
Revises: ca91b9b2d47d
Create Date: 2025-10-25 00:08:05.025985

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9763ce689d3e'
down_revision = 'ca91b9b2d47d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course', 'short_description',
               existing_type=sa.VARCHAR(length=500),
               type_=sqlmodel.sql.sqltypes.AutoString(length=512),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course', 'short_description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=512),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###
