"""CourseDescriptionLine foreign key to Course

Revision ID: ba3a9270fbfc
Revises: baf49c1963a0
Create Date: 2025-10-16 23:36:27.038738

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ba3a9270fbfc'
down_revision = 'baf49c1963a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coursedescriptionline', sa.Column('course_id', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('coursedescriptionline_block_id_fkey'), 'coursedescriptionline', type_='foreignkey')
    op.create_foreign_key(None, 'coursedescriptionline', 'course', ['course_id'], ['id'], ondelete='CASCADE')
    op.drop_column('coursedescriptionline', 'block_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coursedescriptionline', sa.Column('block_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'coursedescriptionline', type_='foreignkey')
    op.create_foreign_key(op.f('coursedescriptionline_block_id_fkey'), 'coursedescriptionline', 'coursedescriptionblock', ['block_id'], ['id'], ondelete='CASCADE')
    op.drop_column('coursedescriptionline', 'course_id')
    # ### end Alembic commands ###
