"""Added social links to User model

Revision ID: c1206036fad4
Revises: a3123637ea9f
Create Date: 2025-10-19 00:08:10.741675

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c1206036fad4'
down_revision = 'a3123637ea9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('website_url', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True))
    op.add_column('users', sa.Column('telegram_url', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True))
    op.add_column('users', sa.Column('github_url', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True))
    op.add_column('users', sa.Column('youtube_url', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'youtube_url')
    op.drop_column('users', 'github_url')
    op.drop_column('users', 'telegram_url')
    op.drop_column('users', 'website_url')
    # ### end Alembic commands ###
