"""Add cover_image to Lesson model

Revision ID: ca91b9b2d47d
Revises: b5e9f3d47c12
Create Date: 2025-10-21 07:53:11.942765

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ca91b9b2d47d'
down_revision = 'b5e9f3d47c12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('cover_image', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # Добавляем столбец language_id с значением по умолчанию 1
    op.add_column('lesson', sa.Column('language_id', sa.Integer(), nullable=False, server_default='1'))
    op.create_foreign_key(None, 'lesson', 'language', ['language_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lesson', type_='foreignkey')
    op.drop_column('lesson', 'language_id')
    op.drop_column('lesson', 'cover_image')
    # ### end Alembic commands ###
