"""Currency model removed

Revision ID: d0d76bef9940
Revises: 515659286e91
Create Date: 2025-10-16 00:13:45.413071

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd0d76bef9940'
down_revision = '515659286e91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('course_currency_id_fkey'), 'course', type_='foreignkey')
    op.drop_column('course', 'currency_id')
    op.drop_index(op.f('ix_currency_code'), table_name='currency')
    op.drop_table('currency')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('currency_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('course_currency_id_fkey'), 'course', 'currency', ['currency_id'], ['id'], ondelete='RESTRICT')
    op.create_table('currency',
    sa.Column('code', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('currency_pkey'))
    )
    op.create_index(op.f('ix_currency_code'), 'currency', ['code'], unique=True)
    # ### end Alembic commands ###
