"""Course add language

Revision ID: d26183712513
Revises: d0d76bef9940
Create Date: 2025-10-16 00:28:13.299695

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd26183712513'
down_revision = 'd0d76bef9940'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('language_id', sa.Integer(), nullable=False, server_default='1'))
    op.create_foreign_key(None, 'course', 'language', ['language_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.drop_column('course', 'language_id')
    # ### end Alembic commands ###
