"""Add is_published flag to Course model

Revision ID: f74551b8c440
Revises: 704e4db1fa07
Create Date: 2025-10-20 04:47:37.638599

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f74551b8c440'
down_revision = '704e4db1fa07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('step',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('step_type', sa.Enum('TEXT', 'VIDEO', 'CODE', 'QUIZ', 'MATCHING', 'SORTING', 'TABLE', 'FILL_BLANKS', 'STRING', 'NUMBER', 'MATH', 'FREE_ANSWER', 'SQL', 'HTML_CSS', 'DATASET', name='steptype'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lesson_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # Добавляем столбец с server_default для существующих записей
    op.add_column('course', sa.Column('is_published', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'is_published')
    op.drop_table('step')
    # ### end Alembic commands ###
