/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as CoursesProgressRouteImport } from './routes/courses.progress'
import { Route as CoursesFavoritesRouteImport } from './routes/courses.favorites'
import { Route as CoursesArchiveRouteImport } from './routes/courses.archive'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutProfileRouteImport } from './routes/_layout/profile'
import { Route as LayoutNotificationsRouteImport } from './routes/_layout/notifications'
import { Route as LayoutNewsRouteImport } from './routes/_layout/news'
import { Route as LayoutMainRouteImport } from './routes/_layout/main'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutCatalogIndexRouteImport } from './routes/_layout/catalog.index'
import { Route as LayoutProfileIdRouteImport } from './routes/_layout/profile.$id'
import { Route as LayoutCourseIdRouteImport } from './routes/_layout/course.$id'
import { Route as LayoutCatalogIdRouteImport } from './routes/_layout/catalog.$id'
import { Route as LayoutCatalogMetaIdRouteImport } from './routes/_layout/catalog.meta.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const CoursesProgressRoute = CoursesProgressRouteImport.update({
  id: '/courses/progress',
  path: '/courses/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesFavoritesRoute = CoursesFavoritesRouteImport.update({
  id: '/courses/favorites',
  path: '/courses/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesArchiveRoute = CoursesArchiveRouteImport.update({
  id: '/courses/archive',
  path: '/courses/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProfileRoute = LayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutNotificationsRoute = LayoutNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutNewsRoute = LayoutNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMainRoute = LayoutMainRouteImport.update({
  id: '/main',
  path: '/main',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCatalogIndexRoute = LayoutCatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProfileIdRoute = LayoutProfileIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LayoutProfileRoute,
} as any)
const LayoutCourseIdRoute = LayoutCourseIdRouteImport.update({
  id: '/course/$id',
  path: '/course/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCatalogIdRoute = LayoutCatalogIdRouteImport.update({
  id: '/catalog/$id',
  path: '/catalog/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCatalogMetaIdRoute = LayoutCatalogMetaIdRouteImport.update({
  id: '/catalog/meta/$id',
  path: '/catalog/meta/$id',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/classes': typeof ClassesRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/main': typeof LayoutMainRoute
  '/news': typeof LayoutNewsRoute
  '/notifications': typeof LayoutNotificationsRoute
  '/profile': typeof LayoutProfileRouteWithChildren
  '/settings': typeof LayoutSettingsRoute
  '/courses/archive': typeof CoursesArchiveRoute
  '/courses/favorites': typeof CoursesFavoritesRoute
  '/courses/progress': typeof CoursesProgressRoute
  '/': typeof LayoutIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/catalog/$id': typeof LayoutCatalogIdRoute
  '/course/$id': typeof LayoutCourseIdRoute
  '/profile/$id': typeof LayoutProfileIdRoute
  '/catalog': typeof LayoutCatalogIndexRoute
  '/catalog/meta/$id': typeof LayoutCatalogMetaIdRoute
}
export interface FileRoutesByTo {
  '/classes': typeof ClassesRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/main': typeof LayoutMainRoute
  '/news': typeof LayoutNewsRoute
  '/notifications': typeof LayoutNotificationsRoute
  '/profile': typeof LayoutProfileRouteWithChildren
  '/settings': typeof LayoutSettingsRoute
  '/courses/archive': typeof CoursesArchiveRoute
  '/courses/favorites': typeof CoursesFavoritesRoute
  '/courses/progress': typeof CoursesProgressRoute
  '/': typeof LayoutIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/catalog/$id': typeof LayoutCatalogIdRoute
  '/course/$id': typeof LayoutCourseIdRoute
  '/profile/$id': typeof LayoutProfileIdRoute
  '/catalog': typeof LayoutCatalogIndexRoute
  '/catalog/meta/$id': typeof LayoutCatalogMetaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/classes': typeof ClassesRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/main': typeof LayoutMainRoute
  '/_layout/news': typeof LayoutNewsRoute
  '/_layout/notifications': typeof LayoutNotificationsRoute
  '/_layout/profile': typeof LayoutProfileRouteWithChildren
  '/_layout/settings': typeof LayoutSettingsRoute
  '/courses/archive': typeof CoursesArchiveRoute
  '/courses/favorites': typeof CoursesFavoritesRoute
  '/courses/progress': typeof CoursesProgressRoute
  '/_layout/': typeof LayoutIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/_layout/catalog/$id': typeof LayoutCatalogIdRoute
  '/_layout/course/$id': typeof LayoutCourseIdRoute
  '/_layout/profile/$id': typeof LayoutProfileIdRoute
  '/_layout/catalog/': typeof LayoutCatalogIndexRoute
  '/_layout/catalog/meta/$id': typeof LayoutCatalogMetaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/classes'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/main'
    | '/news'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/courses/archive'
    | '/courses/favorites'
    | '/courses/progress'
    | '/'
    | '/courses'
    | '/catalog/$id'
    | '/course/$id'
    | '/profile/$id'
    | '/catalog'
    | '/catalog/meta/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/classes'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/main'
    | '/news'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/courses/archive'
    | '/courses/favorites'
    | '/courses/progress'
    | '/'
    | '/courses'
    | '/catalog/$id'
    | '/course/$id'
    | '/profile/$id'
    | '/catalog'
    | '/catalog/meta/$id'
  id:
    | '__root__'
    | '/_layout'
    | '/classes'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/main'
    | '/_layout/news'
    | '/_layout/notifications'
    | '/_layout/profile'
    | '/_layout/settings'
    | '/courses/archive'
    | '/courses/favorites'
    | '/courses/progress'
    | '/_layout/'
    | '/courses/'
    | '/_layout/catalog/$id'
    | '/_layout/course/$id'
    | '/_layout/profile/$id'
    | '/_layout/catalog/'
    | '/_layout/catalog/meta/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  ClassesRoute: typeof ClassesRoute
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  CoursesArchiveRoute: typeof CoursesArchiveRoute
  CoursesFavoritesRoute: typeof CoursesFavoritesRoute
  CoursesProgressRoute: typeof CoursesProgressRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/courses/progress': {
      id: '/courses/progress'
      path: '/courses/progress'
      fullPath: '/courses/progress'
      preLoaderRoute: typeof CoursesProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/favorites': {
      id: '/courses/favorites'
      path: '/courses/favorites'
      fullPath: '/courses/favorites'
      preLoaderRoute: typeof CoursesFavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/archive': {
      id: '/courses/archive'
      path: '/courses/archive'
      fullPath: '/courses/archive'
      preLoaderRoute: typeof CoursesArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/profile': {
      id: '/_layout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof LayoutProfileRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/notifications': {
      id: '/_layout/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof LayoutNotificationsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/news': {
      id: '/_layout/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof LayoutNewsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/main': {
      id: '/_layout/main'
      path: '/main'
      fullPath: '/main'
      preLoaderRoute: typeof LayoutMainRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/catalog/': {
      id: '/_layout/catalog/'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof LayoutCatalogIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/profile/$id': {
      id: '/_layout/profile/$id'
      path: '/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof LayoutProfileIdRouteImport
      parentRoute: typeof LayoutProfileRoute
    }
    '/_layout/course/$id': {
      id: '/_layout/course/$id'
      path: '/course/$id'
      fullPath: '/course/$id'
      preLoaderRoute: typeof LayoutCourseIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/catalog/$id': {
      id: '/_layout/catalog/$id'
      path: '/catalog/$id'
      fullPath: '/catalog/$id'
      preLoaderRoute: typeof LayoutCatalogIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/catalog/meta/$id': {
      id: '/_layout/catalog/meta/$id'
      path: '/catalog/meta/$id'
      fullPath: '/catalog/meta/$id'
      preLoaderRoute: typeof LayoutCatalogMetaIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutProfileRouteChildren {
  LayoutProfileIdRoute: typeof LayoutProfileIdRoute
}

const LayoutProfileRouteChildren: LayoutProfileRouteChildren = {
  LayoutProfileIdRoute: LayoutProfileIdRoute,
}

const LayoutProfileRouteWithChildren = LayoutProfileRoute._addFileChildren(
  LayoutProfileRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutMainRoute: typeof LayoutMainRoute
  LayoutNewsRoute: typeof LayoutNewsRoute
  LayoutNotificationsRoute: typeof LayoutNotificationsRoute
  LayoutProfileRoute: typeof LayoutProfileRouteWithChildren
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutCatalogIdRoute: typeof LayoutCatalogIdRoute
  LayoutCourseIdRoute: typeof LayoutCourseIdRoute
  LayoutCatalogIndexRoute: typeof LayoutCatalogIndexRoute
  LayoutCatalogMetaIdRoute: typeof LayoutCatalogMetaIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutMainRoute: LayoutMainRoute,
  LayoutNewsRoute: LayoutNewsRoute,
  LayoutNotificationsRoute: LayoutNotificationsRoute,
  LayoutProfileRoute: LayoutProfileRouteWithChildren,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutCatalogIdRoute: LayoutCatalogIdRoute,
  LayoutCourseIdRoute: LayoutCourseIdRoute,
  LayoutCatalogIndexRoute: LayoutCatalogIndexRoute,
  LayoutCatalogMetaIdRoute: LayoutCatalogMetaIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  ClassesRoute: ClassesRoute,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  CoursesArchiveRoute: CoursesArchiveRoute,
  CoursesFavoritesRoute: CoursesFavoritesRoute,
  CoursesProgressRoute: CoursesProgressRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
